import sqlite3

DB_PATH = "sales_demo.db"


def get_schema(db_path: str = DB_PATH) -> str:
    with sqlite3.connect(db_path) as conn:
        tables = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
        ).fetchall()

        schema_lines = []
        for (table_name,) in tables:
            columns = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
            schema_lines.append(f"Table: {table_name}")
            for column in columns:
                _, name, data_type, not_null, _, pk = column
                required = "NOT NULL" if not_null else "NULL"
                primary_key = "PRIMARY KEY" if pk else ""
                schema_lines.append(f"  - {name}: {data_type} {required} {primary_key}".rstrip())

        return "\n".join(schema_lines)


def build_prompt(schema: str, question: str) -> str:
    return f"""
You are a Text-to-SQL assistant.
Generate one SQLite SELECT query for the user's question.
Use only the tables and columns listed in the schema.
Do not generate INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, PRAGMA, or ATTACH.
Return only SQL, without markdown.

Schema:
{schema}

Question:
{question}
"""


def demo_generate_sql(question: str) -> str:
    """Small deterministic demo. Replace this function with an LLM API call."""
    normalized = question.lower()

    if "unpaid" in normalized or "pending" in normalized or "owe" in normalized:
        return """
SELECT
  c.name,
  c.email,
  SUM(o.total - o.paid) AS pending_amount
FROM customers c
JOIN orders o ON o.customer_id = c.id
WHERE o.status IN ('pending', 'partial')
GROUP BY c.id, c.name, c.email
HAVING pending_amount > 500
ORDER BY pending_amount DESC
"""

    if "country" in normalized:
        return """
SELECT
  country,
  COUNT(*) AS total_customers
FROM customers
GROUP BY country
ORDER BY total_customers DESC
"""

    if "partial" in normalized:
        return """
SELECT
  c.name,
  o.id AS order_id,
  o.total,
  o.paid,
  o.total - o.paid AS pending_amount
FROM orders o
JOIN customers c ON c.id = o.customer_id
WHERE o.status = 'partial'
ORDER BY pending_amount DESC
"""

    return """
SELECT
  c.name,
  c.email,
  o.order_date,
  o.total,
  o.paid,
  o.status
FROM orders o
JOIN customers c ON c.id = o.customer_id
ORDER BY o.order_date DESC
"""


def is_safe_select(sql: str) -> bool:
    normalized = " ".join(sql.strip().lower().split())
    forbidden = [
        "insert",
        "update",
        "delete",
        "drop",
        "alter",
        "create",
        "replace",
        "truncate",
        "pragma",
        "attach",
        "detach",
    ]

    if not normalized.startswith("select "):
        return False

    return not any(word in normalized for word in forbidden)


def run_safe_query(db_path: str, sql: str) -> list[tuple]:
    if not is_safe_select(sql):
        raise ValueError("Unsafe SQL generated by model")

    safe_sql = sql.strip().rstrip(";")
    if " limit " not in f" {safe_sql.lower()} ":
        safe_sql += " LIMIT 50"

    readonly_uri = f"file:{db_path}?mode=ro"
    with sqlite3.connect(readonly_uri, uri=True) as conn:
        return conn.execute(safe_sql).fetchall()
